# Copyright (c) 2022, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0
channels:
  - rapidsai-nightly
  - dask/label/dev
  - numba
  - conda-forge
  - nvidia

dependencies:
  - dask
  - distributed
  - cudf
  - dask-cudf
  - cupy
  - rmm
  - dask-cuda
  - dask-cudf
  - pynvml>=11.0.0
  - numba>=0.46
  - cudatoolkit=11.2
  - python=3.10
  - setuptools
  - psutil
  - cython>=0.29.14,<3.0.0a0
  - pytest
  - pytest-asyncio
